// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_control                     23
#define gattdb_temperature_measurement         26
#define gattdb_temperature_type                29
#define gattdb_intermediate_temperature         31
#define gattdb_measurement_interval            34
#define gattdb_valid_range                     36
#define gattdb_tx_power_level                  39

#endif
